### ISSUE TITLE
Requirements to run

### ISSUE THREAD

**Issue by athiraunni** [nithinp/game-of-life#1]
Hi Nithin etta,
Gone through the Readme. It's written nicely with small typos like cels<-cells , ho<-how. I am new to this and it would be helpful if you can tell me the requirements to run this game ?

**Comment by ghost** [comment]
Hi,

I just forgot to update requirements in the readme. Sorry for that.

1. [Python](https://www.python.org/)
2. [Pygame](http://www.pygame.org/download.shtml)

These two are the only requirements you need to run this game.

You can  get some sample patterns from [here](https://en.wikipedia.org/wiki/Conway's_Game_of_Life#Examples_of_patterns). Please check this out.

**Comment by athiraunni** [comment]
Thank you  Nithin :)
